//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public int Id { get; set; }
        public Nullable<int> IdStudent { get; set; }
        public Nullable<int> IdSubject { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
